cc_library(
    name = "frames",
    hdrs = [
        "lazy_pre_strong_connection.h",
        "lazy_pre_weak_connection.h",
        "lazy_strong_connection.h",
        "lazy_weak_connection.h",
        "start.h",
        "strong.h",
        "weak.h",
    ],
    visibility = ["//lazyparam_prover/lazy_paramodulation:__subpackages__"],
)
