cc_library(
  name = "frames",
  hdrs = [
    "start.h",
    "strong.h",
    "weak_connections.h",
    "weak_set.h",
    "weak.h",
    "weak_unify.h",
    "min_cost.h",
  ],
  visibility = ["//lazyparam_prover/lazy_paramodulation:__subpackages__"],
)
