cc_library(
    name = "frames",
    hdrs = [
        "start.h",
        "strong.h",
        "weak.h",
        "weak_unify.h",
    ],
    visibility = ["//lazyparam_prover/connection_tableau:__subpackages__"],
)
