cc_library(
    name = "util",
    hdrs = [
        "string.h",
        "types.h",
        "log.h",
        "short.h",
        "read_file.h",
        "time.h",
    ],
    visibility = ["//visibility:public"],
)
