load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["bazel.go"],
    importpath = "github.com/pompon0/tptp_benchmark_go/utils",
    visibility = ["//visibility:public"],
)
